// netlify/functions/generate-recipe.js

// Aris's Blueprint: This function is the secure API endpoint for Acre Lite (Free Tier).
// It verifies the request, checks the conversion limits, and returns a simple recipe.

exports.handler = async (event, context) => {
    
    // 1. INPUT VALIDATION (Security/Aris's Mandate)
    if (event.httpMethod !== "POST" || !event.body) {
        return { 
            statusCode: 405, 
            headers: {
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Methods": "POST, OPTIONS"
            },
            body: JSON.stringify({ error: "Method Not Allowed" }) 
        };
    }

    try {
        const data = JSON.parse(event.body);
        const userQuery = data.query ? data.query.toLowerCase() : ''; 

        if (!userQuery) {
            return { 
                statusCode: 400, 
                headers: {
                    "Access-Control-Allow-Origin": "*",
                    "Access-Control-Allow-Methods": "POST, OPTIONS"
                },
                body: JSON.stringify({ error: "Missing query parameter." }) 
            };
        }

        // 2. CONVERSION LIMIT CHECK (Monetization Protocol)
        // Checks for keywords that require advanced, paywalled personas (Phoebe, Sage, Dr. Kale, Penny).
        const advancedKeywords = [
            "gluten-free", "keto", "vegan", "dairy-free", "7-day", "budget", 
            "nutritional analysis", "shopping list", "bake", "cookie", "cake" 
        ];

        const requiresUpgrade = advancedKeywords.some(keyword => userQuery.includes(keyword));

        if (requiresUpgrade) {
             const upgradeMessage = `
                <div style="padding: 20px; background-color: #fce4e4; border: 1px solid #d32f2f; border-radius: 8px; text-align: center;">
                    <h3 style="color: #d32f2f; margin-top: 0;">Upgrade Required!</h3>
                    <p>That request requires the specialized expertise of our Pro AI Team:</p>
                    <ul style="list-style-type: none; padding: 0; line-height: 1.6;">
                        <li><strong>Phoebe, The Master Baker,</strong> for detailed baking/GF formulas.</li>
                        <li><strong>Sage, The Meal Planner,</strong> for multi-day planning.</li>
                    </ul>
                    <button style="padding: 10px 20px; background-color: #4a2c2a; color: white; border: none; border-radius: 4px; margin-top: 10px; cursor: pointer;">Start Free Trial to Unlock Pro Tools</button>
                </div>
            `;
            return {
                statusCode: 200,
                headers: { 
                    "Content-Type": "application/json",
                    "Access-Control-Allow-Origin": "*",
                    "Access-Control-Allow-Methods": "POST, OPTIONS"
                },
                body: JSON.stringify({ recipe: upgradeMessage })
            };
        }

        // --- 3. HORST ARCHIVE GENERATION (Free Service) ---
        // For now, Acre Lite returns a simple, Horst-approved placeholder.
        const generatedRecipe = `
            <div style="padding: 20px; background-color: #fff0d6; border: 1px solid #a87e5b; border-radius: 8px;">
                <h3 style="color: #4a2c2a; margin-top: 0;">Recipe Generated by Acre Lite (Horst Archive)</h3>
                <p><strong>Query:</strong> ${data.query}</p>
                <hr>
                <p><strong>Protocol:</strong> Start by combining your core ingredients (proteins and vegetables) with a generous amount of seasoning (salt, pepper, and herbs). Roast on a single sheet pan at 400°F for 25 minutes, or pan-sear for 15 minutes. Enjoy your simple, reliable meal!</p>
            </div>
        `;
        // ----------------------------------------------------

        // 4. RETURN RESPONSE: Send the generated content back to the website.
        return {
            statusCode: 200,
            headers: { 
                "Content-Type": "application/json",
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Methods": "POST, OPTIONS"
            },
            body: JSON.stringify({ recipe: generatedRecipe })
        };

    } catch (error) {
        console.error("API Error:", error);
        return { 
            statusCode: 500, 
            headers: {
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Methods": "POST, OPTIONS"
            },
            body: JSON.stringify({ error: "Failed to process request." }) 
        };
    }
};
