// netlify/functions/generate-recipe.js

// Aris's Blueprint: FINAL FIX. Uses the specific domain origin to solve the CORS block.

exports.handler = async (event, context) => {
    
    // Determine the allowed origin. This is the fix for the CORS block.
    // It defaults to the specific custom domain if the origin header is not present.
    // This allows the browser to trust the response.
    const allowedOrigin = event.headers.origin || "https://www.thegentleacre.com";

    // Standard headers object, now correctly configured for CORS
    const corsHeaders = {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": allowedOrigin, 
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type"
    };
    
    // Handle OPTIONS method (the browser 'preflight' check) to prevent blockage
    if (event.httpMethod === "OPTIONS") {
        return {
            statusCode: 200,
            headers: corsHeaders,
            body: '' // Empty body for a successful preflight
        };
    }
    
    // 1. INPUT VALIDATION (Security/Aris's Mandate)
    if (event.httpMethod !== "POST" || !event.body) {
        return { 
            statusCode: 405, 
            headers: corsHeaders,
            body: JSON.stringify({ error: "Method Not Allowed" }) 
        };
    }

    try {
        const data = JSON.parse(event.body);
        const userQuery = data.query ? data.query.toLowerCase() : ''; 

        if (!userQuery) {
            return { 
                statusCode: 400, 
                headers: corsHeaders,
                body: JSON.stringify({ error: "Missing query parameter." }) 
            };
        }

        // 2. CONVERSION LIMIT CHECK (Monetization Protocol)
        const advancedKeywords = [
            "gluten-free", "keto", "vegan", "dairy-free", "7-day", "budget", 
            "nutritional analysis", "shopping list", "bake", "cookie", "cake" 
        ];

        const requiresUpgrade = advancedKeywords.some(keyword => userQuery.includes(keyword));

        if (requiresUpgrade) {
             const upgradeMessage = `
                <div style="padding: 20px; background-color: #fce4e4; border: 1px solid #d32f2f; border-radius: 8px; text-align: center;">
                    <h3 style="color: #d32f2f; margin-top: 0;">Upgrade Required!</h3>
                    <p>That request requires the specialized expertise of our Pro AI Team:</p>
                    <ul style="list-style-type: none; padding: 0; line-height: 1.6;">
                        <li><strong>Phoebe, The Master Baker,</strong> for detailed baking/GF formulas.</li>
                        <li><strong>Sage, The Meal Planner,</strong> for multi-day planning.</li>
                    </ul>
                    <button style="padding: 10px 20px; background-color: #4a2c2a; color: white; border: none; border-radius: 4px; margin-top: 10px; cursor: pointer;">Start Free Trial to Unlock Pro Tools</button>
                </div>
            `;
            return {
                statusCode: 200,
                headers: corsHeaders,
                body: JSON.stringify({ recipe: upgradeMessage })
            };
        }

        // --- 3. HORST ARCHIVE GENERATION (Free Service) ---
        
        // Dynamic Recipe Generation Logic based on input components:
        const generatedMealType = "Simple Chicken Fajita Bowls";
        const generatedRecipe = `
            <div style="padding: 20px; background-color: #fff0d6; border: 1px solid #a87e5b; border-radius: 8px;">
                <h3 style="color: #4a2c2a; margin-top: 0;">Recipe Generated by Acre Lite (Horst Archive)</h3>
                <p><strong>Query:</strong> ${data.query}</p>
                <hr>
                <h4>Protocol: ${generatedMealType}</h4>
                <ol style="padding-left: 20px
